:- use_module(library(clpfd)).

plan(Days, Gender, Lec, LecN, LecS):-
  Days = [M, T, W, Th, Fr],
  Gender = [_, _, _, _, _],
  Lec = [_, Phs, Modern, Nutr, Study],
  LecN = [Alice, Bernadette, Charles, Duane, Eddie],
  LecS = [Felicidad, _, Haller, Itakura, Jeffreys],
  Lec ins 1..5, 
  LecN ins 1..5, 
  LecS ins 1..5, 
  Gender ins 1..2,
  M#=1, T#=2, W#=3, Th#=4, Fr#=5,
  all_different(Lec), all_different(LecN), 
  all_different(LecS), 
  Alice#=M,
  Charles #\=Fr, Charles #\=Phs, 
  Jeffreys #=Nutr,
  element(Modern, Gender, 1), 
  element(Itakura, Gender, 2),
  Study #\= Itakura,
  Study #= Itakura - 1 #<==> K1,
  Itakura #=  Study - 1 #<==> K2,
  K1 + K2 #=1, 
  Haller - Eddie #>0, 
  Haller #\= Eddie, 
  Duane #= Felicidad, 
  Duane - Modern #< 0 , 
  element(Alice, Gender, 2), element(Bernadette, Gender, 2), 
    element(Charles,Gender,1) ,element(Duane,Gender,1) ,element(Eddie,Gender,1) , 
  labeling([], Lec), labeling([], LecN), labeling([], LecS), labeling([], Gender).
